# Home work 1 of Data Science module

In [2]:
# 1.Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
import numpy as np
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
# 2.Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
a= np.zeros((3,3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [19]:
# 3.Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
a=np.random.randint(low=1, high=11, size=(5,5), dtype=int)
print(a)

[[ 9  8  2  1 10]
 [ 8  5  5  3  1]
 [ 8 10  6  4  4]
 [ 1  2  9  6  9]
 [ 2  1  3  9  5]]


In [5]:
# 4.Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
a=np.random.random((4,4))
print(a)

[[0.83888874 0.04696069 0.47554978 0.45896757]
 [0.90311288 0.714319   0.17317397 0.05645629]
 [0.29619455 0.95361947 0.59845669 0.21112653]
 [0.6832128  0.50544483 0.78615456 0.07343081]]


In [24]:
# 5.Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
a = np.random.randint(low=1, high=11, size=5)
b = np.random.randint(low=1, high=11, size=5)
print('vector', a)
print('vector', b)
print('Addition a+b', a+b)
print('Subtraction a-b', a-b)
print('Multiplication, a*b', a*b)

vector [4 5 6 9 4]
vector [10  8  5  9  5]
Addition a+b [14 13 11 18  9]
Subtraction a-b [-6 -3  1  0 -1]
Multiplication, a*b [40 40 30 81 20]


In [22]:
# 6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
a= np.random.randint(low=1, high=10, size=7)
b= np.random.randint(low=1, high=10, size=7)
print('vector', a)
print('vector', b)
print('Dot product', np.dot(a,b) )

vector [3 4 9 6 2 3 2]
vector [7 3 5 6 8 4 3]
Dot product 148


In [26]:
#7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
a= np.random.randint(low=1, high=11, size=(2,2))
b= np.random.randint(low=1, high=11, size=(2,3))
print(a)
print()
print(b)
print()
print ('Multiplication\n', np.dot(a,b))

[[10  1]
 [ 8  9]]

[[ 1  1  5]
 [10  3  5]]

Multiplication
 [[20 13 55]
 [98 35 85]]


In [27]:
# 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю
a = np.random.randint(low=1, high=11, size=(3,3))
print(a)
a_inv=np.linalg.inv(a)
print(a_inv)

[[10 10  7]
 [ 2  1  4]
 [10  6  9]]
[[-0.17857143 -0.57142857  0.39285714]
 [ 0.26190476  0.23809524 -0.30952381]
 [ 0.02380952  0.47619048 -0.11904762]]


In [10]:
# 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
a = np.random.random((4,4))
print(a)
print()
a_trans=a.T
print(a_trans)

[[0.73323201 0.07270126 0.53735432 0.84685747]
 [0.86441815 0.20516447 0.73736255 0.94366865]
 [0.65541002 0.25522225 0.57189343 0.02225638]
 [0.7125473  0.48563053 0.64801919 0.92816628]]

[[0.73323201 0.86441815 0.65541002 0.7125473 ]
 [0.07270126 0.20516447 0.25522225 0.48563053]
 [0.53735432 0.73736255 0.57189343 0.64801919]
 [0.84685747 0.94366865 0.02225638 0.92816628]]


In [28]:
#10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
a= np.random.randint(low=1, high=11, size=(3,4))
b= np.random.randint(low=1, high=11, size=4)
print(a)
print()
print(b,'\n')
print('Multiplication\n', np.dot(a,b))                 

[[ 3  9  5  3]
 [ 1 10  3  1]
 [ 1  1  9  2]]

[7 6 5 3] 

Multiplication
 [109  85  64]


In [12]:
#11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
a = np.random.random((2,3))
b = np.random.random(3)
print(a,'\n')
print(b,'\n')
print('Multiplication\n', np.dot(a,b))

[[0.29515515 0.71412423 0.85903519]
 [0.44568142 0.4212859  0.20356109]] 

[0.88472012 0.10936645 0.31408449] 

Multiplication
 [0.60904056 0.50431324]


In [29]:
#12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
a=np.random.randint(low=1, high=11, size=(2,2))
b=np.random.randint(low=1, high=11, size=(2,2))
print('Matrix a\n',a,'\n')
print('Matrix b\n',b,'\n')
print('Multiplication\n', a*b)

vector a
 [[ 9 10]
 [ 1  2]] 

vector b
 [[2 4]
 [6 6]] 

Multiplication
 [[18 40]
 [ 6 12]]


In [30]:
#13.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
a=np.random.randint(low=1, high=11, size=(2,2))
b=np.random.randint(low=1, high=11, size=(2,2))
print('Matrix a\n',a,'\n')
print('Matrix b\n',b,'\n')
print('Multiplication\n', np.dot(a,b))
 

vector a
 [[4 9]
 [1 2]] 

vector b
 [[ 5 10]
 [ 6  2]] 

Multiplication
 [[74 58]
 [17 14]]


In [32]:
#14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
a = np.random.randint(low=1, high=101, size=(5,5))
print('Matrix a\n',a,'\n')
print('Sum\n', a.sum())

vector a
 [[ 6 53 93 31 23]
 [ 8 25 60 87  2]
 [10 64  4 85 18]
 [39 64 20 77 86]
 [80 86 80 45 91]] 

Sum
 1237


In [33]:
#15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
a=np.random.randint(low=1, high=11, size=(4,4))
b=np.random.randint(low=1, high=11, size=(4,4))
print('Matrix a\n',a,'\n')
print('Matrix b\n',b,'\n')
print('Subtraction\n', a-b)

vector a
 [[ 5  4  8  6]
 [ 8  1  1 10]
 [ 4  3  1  6]
 [ 1 10  5  4]] 

vector b
 [[3 3 5 8]
 [4 9 8 2]
 [7 1 7 1]
 [1 7 1 5]] 

Subtraction
 [[ 2  1  3 -2]
 [ 4 -8 -7  8]
 [-3  2 -6  5]
 [ 0  3  4 -1]]


In [17]:
#16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
a =np.random.random((3,3))
print('Matrix a\n',a,'\n')
b=np.array([
    [sum(a[0,:])],
    [sum(a[1,:])], 
    [sum(a[2,:])]
])
print(b)

vector a
 [[0.43207389 0.30294481 0.70628723]
 [0.66865526 0.33464678 0.01720251]
 [0.5504241  0.21008245 0.45043555]] 

[[1.44130592]
 [1.02050455]
 [1.21094209]]


In [35]:
#17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
a= np.random.randint(low=1, high=10, size=(3,4))
print('Matrix a\n',a,'\n')
a2=np.zeros((3,4), dtype=int)
for i in range(a.shape[0]):    
    for j in range(a.shape[1]):
       a2[i,j]=a[i,j]**2
print('Matrix A power 2\n',a2)


Matrix a
 [[5 8 1 9]
 [4 9 7 6]
 [9 2 2 8]] 

Matrix A power 2
 [[25 64  1 81]
 [16 81 49 36]
 [81  4  4 64]]


In [48]:
#18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел
a=np.random.randint(low=1, high=51, size=4)
print('Vector a\n',a,'\n')
b=np.zeros(4)
for i in range(a.shape[0]):
    b[i]=a[i]**0.5    
print('SQRT of Vector a\n',b)

Vector a
 [41 41 45  2] 

SQRT of Vector a
 [6.40312424 6.40312424 6.70820393 1.41421356]
